### ISSUE TITLE
Initial `MoodleBackupParser`

### ISSUE THREAD

**Issue by nfreear** [IET-OU/moodle-backup-parser#1]
_Note_: features and todos are currently driven by the OU's Applaud project.

see: [not planned](#not-planned)
### Features / todos
1. [x] — initial parser;
2. [x] — initial static pages generator;
3. [x] — initial unit tests, php-lint, Travis-CI;
4. [x] — add test fixture/ `MBZ`; integrate unit tests into Travis-CI build — Bug: #2;
5. [x] — expand links/ images in HTML — implement `StaticPages::expandLinks(..)`;
6. [x] — Extend `Clean::html(..)` — use it to remove `face`, `color` HTML attributes, etc., as well as `style=".."`;
7. [x] — handle `sections` in Moodle backups — Bug: #4;
8. [x] — handle `labels` from Moodle backups;
9. [x] — handle `files` from backups;
10. [x] — handle `resource` activities from backups;
11. [x] — handle `folder` activities from backups;
12. [x] — handle `urls` from backups — including eg. YouTube embeds;
13. [ ] — Todo: support for `mod_subpage` — https://github.com/moodleou/moodle-mod_subpage
14. [ ] — Todo: decide what other `activity` types we need?! — minimum, 4 or 5? `page`, `label`, `url`, `file`, `mod_subpage`;
15. [x] — handle `oublog`, `oucollaborate`, `forumng` — just replace with configurable URLs — Bug: #6;
16. [x] — arbitrary search & replace in HTML content — Bug #8;
17. [x] — auto-expand abbreviations — Bug #12;
18. [ ] — split/chunk course home-page into per-section pages — Bug #14;
19. [ ] — Todo: deal with filename clashes;
20. [ ] — Todo: `CLI` command-line interface?
21. ...
## 
### Not planned

Features that we do _NOT_ have immediate plans to add:
- Generally, user-generated content;
- For example, forum, forum posts, wikis ...
## 
- https://travis-ci.org/IET-OU/moodle-backup-parser
- https://phpunit.de/manual/current/en/appendixes.assertions.html

---

[[iet:5621274](https://iet.teamwork.com/tasks/5621274)]
